version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_booking
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/event_booking
      - JWT_SECRET=your-secret-key
    volumes:
      - ./apps/backend:/usr/src/app/apps/backend
      - /usr/src/app/apps/backend/node_modules
  
  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./apps/web:/usr/src/app/apps/web
      - /usr/src/app/apps/web/node_modules

volumes:
  postgres_data: